package protocol

// The cross-language proof.
//
// zod cannot run in Go, so the structs are hand-written and the defaults are
// generated from a schema — two translations of the same document. When they
// disagree NOTHING IS THROWN: a field comes out `0` where the contract says
// `null`, and a host that failed to measure its CPU reads on the dashboard as
// healthy and idle. That is the one lie this system must not tell an operator.
//
// So the frames live as data, in packages/protocol/conformance, and both
// languages read the same files. `cases/` is hand-written (a corpus generated
// from the schema would only ever probe what the schema already thought of);
// `expected/` is generated by running the frames through zod, so a diff there is
// a behaviour change and shows up in review.
//
// WHY THE CORPUS IS NOT EMBEDDED, WHILE THE SCHEMA IS: the schema has to travel
// with the binary — it validates frames on a machine where this repository does
// not exist. The corpus is test-only, and a second copy of it could drift from
// the first, which would quietly weaken the very thing it proves.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

const corpusDir = "../../../packages/protocol/conformance"

type conformanceCase struct {
	ID        string          `json:"id"`
	Direction string          `json:"direction"`
	Expect    string          `json:"expect"`
	Why       string          `json:"why"`
	Frame     json.RawMessage `json:"frame"`
}

type caseFile struct {
	Description string            `json:"description"`
	Cases       []conformanceCase `json:"cases"`
}

type expectationFile struct {
	// Accepted IS the contract: the same input must normalise to this value in
	// both languages. Keys are sorted recursively, so field order is not a
	// contract and comparison happens on decoded values, never on bytes.
	Accepted map[string]json.RawMessage `json:"accepted"`
	// Rejected is a zod diagnostic string, kept for a human reading the file.
	// Go asserts only THAT a frame was refused, never the wording.
	Rejected map[string]string `json:"rejected"`
}

func TestConformanceCorpus(t *testing.T) {
	bundles := []string{"upstream-accept", "upstream-reject", "downstream-accept", "downstream-reject"}
	total := 0

	for _, bundle := range bundles {
		var cases caseFile
		readJSON(t, filepath.Join(corpusDir, "cases", bundle+".json"), &cases)
		var expectations expectationFile
		readJSON(t, filepath.Join(corpusDir, "expected", bundle+".json"), &expectations)

		if len(cases.Cases) == 0 {
			t.Fatalf("%s has no cases", bundle)
		}
		total += len(cases.Cases)

		for _, testCase := range cases.Cases {
			t.Run("[TC-PDAGENT-049] "+bundle+"/"+testCase.ID, func(t *testing.T) {
				switch testCase.Expect {
				case "accept":
					want, ok := expectations.Accepted[testCase.ID]
					if !ok {
						t.Fatalf("no expectation for %q — regenerate expected/ (`npm run expect:build -w @pdmux/protocol`)", testCase.ID)
					}
					checkAccepted(t, testCase, want)
				case "reject":
					if _, ok := expectations.Rejected[testCase.ID]; !ok {
						t.Fatalf("no expectation for %q — regenerate expected/", testCase.ID)
					}
					checkRejected(t, testCase)
				default:
					t.Fatalf("case %q has expect=%q, want accept or reject", testCase.ID, testCase.Expect)
				}
			})
		}

		// A corpus that lies is worse than no corpus: an expectation with no case
		// silently stops being checked.
		known := map[string]bool{}
		for _, testCase := range cases.Cases {
			known[testCase.ID] = true
		}
		for id := range expectations.Accepted {
			if !known[id] {
				t.Errorf("%s: expected/ has %q but cases/ does not", bundle, id)
			}
		}
		for id := range expectations.Rejected {
			if !known[id] {
				t.Errorf("%s: expected/ has %q but cases/ does not", bundle, id)
			}
		}
	}

	t.Logf("checked %d conformance frames against the TypeScript contract", total)
}

// checkAccepted is the whole point: decode with the Go reader, apply the Go
// defaults, and land on the value zod produced from the same bytes.
func checkAccepted(t *testing.T, testCase conformanceCase, want json.RawMessage) {
	t.Helper()
	frame, err := decodeDirection(t, testCase)
	if err != nil {
		t.Fatalf("rejected a frame the contract accepts (%s): %v", testCase.Why, err)
	}
	got, err := json.Marshal(frame)
	if err != nil {
		t.Fatalf("re-encoding: %v", err)
	}
	// Compared as decoded values so neither key order nor the spelling of a
	// number (1e6 vs 1000000) can fail a run for no reason.
	if gotValue, wantValue := decodeAny(t, got), decodeAny(t, want); !reflect.DeepEqual(gotValue, wantValue) {
		t.Errorf("normalised differently from the TypeScript contract.\n why: %s\n  go: %s\n  ts: %s",
			testCase.Why, indent(t, got), indent(t, want))
	}
}

func checkRejected(t *testing.T, testCase conformanceCase) {
	t.Helper()
	if _, err := decodeDirection(t, testCase); err == nil {
		t.Errorf("accepted a frame the contract refuses.\n why: %s\nframe: %s", testCase.Why, indent(t, testCase.Frame))
	}
}

func decodeDirection(t *testing.T, testCase conformanceCase) (any, error) {
	t.Helper()
	switch testCase.Direction {
	case "upstream":
		return DecodeUpstream(testCase.Frame)
	case "downstream":
		return DecodeDownstream(testCase.Frame)
	default:
		t.Fatalf("case %q has direction %q, want upstream or downstream", testCase.ID, testCase.Direction)
		return nil, nil
	}
}

func readJSON(t *testing.T, path string, out any) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading the conformance corpus: %v", err)
	}
	if err := json.Unmarshal(data, out); err != nil {
		t.Fatalf("%s: %v", path, err)
	}
}

func decodeAny(t *testing.T, data []byte) any {
	t.Helper()
	var value any
	if err := json.Unmarshal(data, &value); err != nil {
		t.Fatalf("decoding for comparison: %v", err)
	}
	return value
}

func indent(t *testing.T, data []byte) string {
	t.Helper()
	var value any
	if err := json.Unmarshal(data, &value); err != nil {
		return string(data)
	}
	pretty, err := json.MarshalIndent(value, "       ", "  ")
	if err != nil {
		return string(data)
	}
	return string(pretty)
}
