// Code generated by internal/protocol/gen. DO NOT EDIT.
//
// Source: packages/protocol/schema (generated in turn from packages/protocol/src/index.ts).
// Regenerate with: go generate ./internal/protocol

package protocol

// The values a schema cannot express, and therefore the first things to drift:
// the header an agent authenticates with, the paths it dials, the caps it applies
// before anything crosses the wire.

const (
	AgentCloseHostDeleted  = 4004
	AgentCloseHostDisabled = 4002
	AgentCloseReplaced     = 4000
	AgentCloseTokenRevoked = 4003
	AgentKeyHeader         = "x-api-key"
	AgentWSPath            = "/agent/ws"
	DiffCapsMaxBytes       = 200000
	DiffCapsMaxFileLines   = 800
	DiffCapsMaxLineChars   = 500
	ExecOutputMax          = 64000
	MinSupportedAgent      = "0.1.0-0"
	ProtocolVersion        = 1
	TerminalWSPath         = "/terminal/ws"
)
