// Code generated by internal/protocol/gen. DO NOT EDIT.
//
// Source: packages/protocol/schema (generated in turn from packages/protocol/src/index.ts).
// Regenerate with: go generate ./internal/protocol

package protocol

import "encoding/json"

// NewAgentConfig returns a new AgentConfig, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewAgentConfig() AgentConfig {
	var value AgentConfig
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero AgentConfig.
func (x *AgentConfig) applyDefaults() {
	x.BodyMaxChars = 1200
	x.GitDetailBudget = 120
	x.GitIntervalSec = 120
	x.GitLimit = 300
	x.GitRoots = []string{}
	x.HeartbeatSec = 5
	x.ProbeTimeoutMs = 2000
	x.Services = []AgentServiceConfig{}
	x.StatusFileCap = 300
	x.TerminalBufferBytes = 262144
	x.UsageIntervalSec = 60
	x.UsageProviders = []string{}
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so AgentConfig inside a list is defaulted exactly like one at the root.
func (x *AgentConfig) UnmarshalJSON(data []byte) error {
	*x = AgentConfig{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain AgentConfig
	return json.Unmarshal(data, (*plain)(x))
}

// NewAgentDiagnostic returns a new AgentDiagnostic, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewAgentDiagnostic() AgentDiagnostic {
	var value AgentDiagnostic
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero AgentDiagnostic.
func (x *AgentDiagnostic) applyDefaults() {
	x.Level = "info"
	x.Message = ""
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so AgentDiagnostic inside a list is defaulted exactly like one at the root.
func (x *AgentDiagnostic) UnmarshalJSON(data []byte) error {
	*x = AgentDiagnostic{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain AgentDiagnostic
	return json.Unmarshal(data, (*plain)(x))
}

// NewAgentExec returns a new AgentExec, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewAgentExec() AgentExec {
	var value AgentExec
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero AgentExec.
func (x *AgentExec) applyDefaults() {
	x.Args = []string{}
	x.Cwd = nil
	x.TimeoutMs = 30000
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so AgentExec inside a list is defaulted exactly like one at the root.
func (x *AgentExec) UnmarshalJSON(data []byte) error {
	*x = AgentExec{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain AgentExec
	return json.Unmarshal(data, (*plain)(x))
}

// NewAgentHello returns a new AgentHello, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewAgentHello() AgentHello {
	var value AgentHello
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero AgentHello.
func (x *AgentHello) applyDefaults() {
	x.Address = ""
	x.Capabilities = []AgentCapability{}
	x.Update.applyDefaults()
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so AgentHello inside a list is defaulted exactly like one at the root.
func (x *AgentHello) UnmarshalJSON(data []byte) error {
	*x = AgentHello{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain AgentHello
	return json.Unmarshal(data, (*plain)(x))
}

// NewAgentServiceConfig returns a new AgentServiceConfig, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewAgentServiceConfig() AgentServiceConfig {
	var value AgentServiceConfig
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero AgentServiceConfig.
func (x *AgentServiceConfig) applyDefaults() {
	x.Path = "/"
	x.Probe = "tcp"
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so AgentServiceConfig inside a list is defaulted exactly like one at the root.
func (x *AgentServiceConfig) UnmarshalJSON(data []byte) error {
	*x = AgentServiceConfig{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain AgentServiceConfig
	return json.Unmarshal(data, (*plain)(x))
}

// NewAgentUpdate returns a new AgentUpdate, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewAgentUpdate() AgentUpdate {
	var value AgentUpdate
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero AgentUpdate.
func (x *AgentUpdate) applyDefaults() {
	x.Force = false
	x.ProbationSec = 300
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so AgentUpdate inside a list is defaulted exactly like one at the root.
func (x *AgentUpdate) UnmarshalJSON(data []byte) error {
	*x = AgentUpdate{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain AgentUpdate
	return json.Unmarshal(data, (*plain)(x))
}

// NewAgentUpdateAbility returns a new AgentUpdateAbility, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewAgentUpdateAbility() AgentUpdateAbility {
	var value AgentUpdateAbility
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero AgentUpdateAbility.
func (x *AgentUpdateAbility) applyDefaults() {
	x.CanRestart = false
	x.RestartMode = "none"
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so AgentUpdateAbility inside a list is defaulted exactly like one at the root.
func (x *AgentUpdateAbility) UnmarshalJSON(data []byte) error {
	*x = AgentUpdateAbility{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain AgentUpdateAbility
	return json.Unmarshal(data, (*plain)(x))
}

// NewAgentUsage returns a new AgentUsage, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewAgentUsage() AgentUsage {
	var value AgentUsage
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero AgentUsage.
func (x *AgentUsage) applyDefaults() {
	x.Processes = 0
	x.Ts = nil
	x.Windows = []UsageWindow{}
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so AgentUsage inside a list is defaulted exactly like one at the root.
func (x *AgentUsage) UnmarshalJSON(data []byte) error {
	*x = AgentUsage{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain AgentUsage
	return json.Unmarshal(data, (*plain)(x))
}

// NewCommitDetail returns a new CommitDetail, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewCommitDetail() CommitDetail {
	var value CommitDetail
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero CommitDetail.
func (x *CommitDetail) applyDefaults() {
	x.AuthorEmail = ""
	x.Body = ""
	x.BodyTruncated = false
	x.Committer = ""
	x.CommitterDate = nil
	x.CommitterEmail = ""
	x.Dropped = 0
	x.Empty = false
	x.Files = []DiffFile{}
	x.Subject = ""
	x.Truncated = false
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so CommitDetail inside a list is defaulted exactly like one at the root.
func (x *CommitDetail) UnmarshalJSON(data []byte) error {
	*x = CommitDetail{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain CommitDetail
	return json.Unmarshal(data, (*plain)(x))
}

// NewDiffFile returns a new DiffFile, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewDiffFile() DiffFile {
	var value DiffFile
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero DiffFile.
func (x *DiffFile) applyDefaults() {
	x.Add = 0
	x.Binary = false
	x.Del = 0
	x.Lines = []string{}
	x.OldPath = nil
	x.Status = "M"
	x.Truncated = false
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so DiffFile inside a list is defaulted exactly like one at the root.
func (x *DiffFile) UnmarshalJSON(data []byte) error {
	*x = DiffFile{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain DiffFile
	return json.Unmarshal(data, (*plain)(x))
}

// NewExecResult returns a new ExecResult, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewExecResult() ExecResult {
	var value ExecResult
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero ExecResult.
func (x *ExecResult) applyDefaults() {
	x.Code = nil
	x.Message = ""
	x.Stderr = ""
	x.Stdout = ""
	x.TimedOut = false
	x.Truncated = false
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so ExecResult inside a list is defaulted exactly like one at the root.
func (x *ExecResult) UnmarshalJSON(data []byte) error {
	*x = ExecResult{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain ExecResult
	return json.Unmarshal(data, (*plain)(x))
}

// NewGitBlob returns a new GitBlob, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewGitBlob() GitBlob {
	var value GitBlob
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero GitBlob.
func (x *GitBlob) applyDefaults() {
	x.Binary = false
	x.Bytes = 0
	x.Error = nil
	x.Lines = []string{}
	x.Truncated = false
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so GitBlob inside a list is defaulted exactly like one at the root.
func (x *GitBlob) UnmarshalJSON(data []byte) error {
	*x = GitBlob{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain GitBlob
	return json.Unmarshal(data, (*plain)(x))
}

// NewGitCommit returns a new GitCommit, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewGitCommit() GitCommit {
	var value GitCommit
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero GitCommit.
func (x *GitCommit) applyDefaults() {
	x.Author = ""
	x.Date = nil
	x.Parents = []string{}
	x.Refs = []string{}
	x.Subject = ""
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so GitCommit inside a list is defaulted exactly like one at the root.
func (x *GitCommit) UnmarshalJSON(data []byte) error {
	*x = GitCommit{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain GitCommit
	return json.Unmarshal(data, (*plain)(x))
}

// NewGitHead returns a new GitHead, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewGitHead() GitHead {
	var value GitHead
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero GitHead.
func (x *GitHead) applyDefaults() {
	x.Ahead = nil
	x.Behind = nil
	x.Branch = nil
	x.Detached = false
	x.Sha = nil
	x.Upstream = nil
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so GitHead inside a list is defaulted exactly like one at the root.
func (x *GitHead) UnmarshalJSON(data []byte) error {
	*x = GitHead{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain GitHead
	return json.Unmarshal(data, (*plain)(x))
}

// NewGitRef returns a new GitRef, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewGitRef() GitRef {
	var value GitRef
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero GitRef.
func (x *GitRef) applyDefaults() {
	x.Ahead = nil
	x.Behind = nil
	x.Gone = false
	x.Upstream = nil
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so GitRef inside a list is defaulted exactly like one at the root.
func (x *GitRef) UnmarshalJSON(data []byte) error {
	*x = GitRef{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain GitRef
	return json.Unmarshal(data, (*plain)(x))
}

// NewGitRemoteCheck returns a new GitRemoteCheck, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewGitRemoteCheck() GitRemoteCheck {
	var value GitRemoteCheck
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero GitRemoteCheck.
func (x *GitRemoteCheck) applyDefaults() {
	x.Error = nil
	x.Refs = []GitRemoteRef{}
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so GitRemoteCheck inside a list is defaulted exactly like one at the root.
func (x *GitRemoteCheck) UnmarshalJSON(data []byte) error {
	*x = GitRemoteCheck{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain GitRemoteCheck
	return json.Unmarshal(data, (*plain)(x))
}

// NewGitRemoteRef returns a new GitRemoteRef, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewGitRemoteRef() GitRemoteRef {
	var value GitRemoteRef
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero GitRemoteRef.
func (x *GitRemoteRef) applyDefaults() {
	x.Kind = "branch"
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so GitRemoteRef inside a list is defaulted exactly like one at the root.
func (x *GitRemoteRef) UnmarshalJSON(data []byte) error {
	*x = GitRemoteRef{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain GitRemoteRef
	return json.Unmarshal(data, (*plain)(x))
}

// NewGitStatusFile returns a new GitStatusFile, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewGitStatusFile() GitStatusFile {
	var value GitStatusFile
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero GitStatusFile.
func (x *GitStatusFile) applyDefaults() {
	x.X = " "
	x.Y = " "
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so GitStatusFile inside a list is defaulted exactly like one at the root.
func (x *GitStatusFile) UnmarshalJSON(data []byte) error {
	*x = GitStatusFile{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain GitStatusFile
	return json.Unmarshal(data, (*plain)(x))
}

// NewGitTree returns a new GitTree, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewGitTree() GitTree {
	var value GitTree
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero GitTree.
func (x *GitTree) applyDefaults() {
	x.Dropped = 0
	x.Entries = []GitTreeEntry{}
	x.Error = nil
	x.Truncated = false
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so GitTree inside a list is defaulted exactly like one at the root.
func (x *GitTree) UnmarshalJSON(data []byte) error {
	*x = GitTree{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain GitTree
	return json.Unmarshal(data, (*plain)(x))
}

// NewGitTreeEntry returns a new GitTreeEntry, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewGitTreeEntry() GitTreeEntry {
	var value GitTreeEntry
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero GitTreeEntry.
func (x *GitTreeEntry) applyDefaults() {
	x.Size = 0
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so GitTreeEntry inside a list is defaulted exactly like one at the root.
func (x *GitTreeEntry) UnmarshalJSON(data []byte) error {
	*x = GitTreeEntry{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain GitTreeEntry
	return json.Unmarshal(data, (*plain)(x))
}

// NewGitUncommitted returns a new GitUncommitted, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewGitUncommitted() GitUncommitted {
	var value GitUncommitted
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero GitUncommitted.
func (x *GitUncommitted) applyDefaults() {
	x.Conflicts = 0
	x.Dropped = 0
	x.Files = []GitStatusFile{}
	x.Staged = 0
	x.Submodules = 0
	x.Total = 0
	x.Unstaged = 0
	x.Untracked = 0
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so GitUncommitted inside a list is defaulted exactly like one at the root.
func (x *GitUncommitted) UnmarshalJSON(data []byte) error {
	*x = GitUncommitted{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain GitUncommitted
	return json.Unmarshal(data, (*plain)(x))
}

// NewHeartbeat returns a new Heartbeat, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewHeartbeat() Heartbeat {
	var value Heartbeat
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero Heartbeat.
func (x *Heartbeat) applyDefaults() {
	x.Diagnostics = []AgentDiagnostic{}
	x.Resource.applyDefaults()
	x.Services = []ServiceProbe{}
	x.Sessions = []MuxSession{}
	x.Usage = []AgentUsage{}
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so Heartbeat inside a list is defaulted exactly like one at the root.
func (x *Heartbeat) UnmarshalJSON(data []byte) error {
	*x = Heartbeat{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain Heartbeat
	return json.Unmarshal(data, (*plain)(x))
}

// NewListener returns a new Listener, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewListener() Listener {
	var value Listener
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero Listener.
func (x *Listener) applyDefaults() {
	x.LoopbackOnly = false
	x.Process = ""
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so Listener inside a list is defaulted exactly like one at the root.
func (x *Listener) UnmarshalJSON(data []byte) error {
	*x = Listener{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain Listener
	return json.Unmarshal(data, (*plain)(x))
}

// NewMuxSession returns a new MuxSession, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewMuxSession() MuxSession {
	var value MuxSession
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero MuxSession.
func (x *MuxSession) applyDefaults() {
	x.Attached = 0
	x.Windows = 0
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so MuxSession inside a list is defaulted exactly like one at the root.
func (x *MuxSession) UnmarshalJSON(data []byte) error {
	*x = MuxSession{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain MuxSession
	return json.Unmarshal(data, (*plain)(x))
}

// NewRepoSnapshot returns a new RepoSnapshot, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewRepoSnapshot() RepoSnapshot {
	var value RepoSnapshot
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero RepoSnapshot.
func (x *RepoSnapshot) applyDefaults() {
	x.Blob = nil
	x.Commits = []GitCommit{}
	x.Details = []CommitDetail{}
	x.Error = nil
	x.Head.applyDefaults()
	x.Limit = 300
	x.Partial = false
	x.Pending = 0
	x.Refs = []GitRef{}
	x.Remote = nil
	x.Tree = nil
	x.Truncated = false
	x.Uncommitted = nil
	x.WorkingDiff = nil
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so RepoSnapshot inside a list is defaulted exactly like one at the root.
func (x *RepoSnapshot) UnmarshalJSON(data []byte) error {
	*x = RepoSnapshot{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain RepoSnapshot
	return json.Unmarshal(data, (*plain)(x))
}

// NewResource returns a new Resource, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewResource() Resource {
	var value Resource
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero Resource.
func (x *Resource) applyDefaults() {
	x.CPUPct = nil
	x.DiskPct = nil
	x.DiskTotalBytes = nil
	x.DiskUsedBytes = nil
	x.Load1 = nil
	x.MemPct = nil
	x.MemTotalBytes = nil
	x.MemUsedBytes = nil
	x.UptimeSec = nil
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so Resource inside a list is defaulted exactly like one at the root.
func (x *Resource) UnmarshalJSON(data []byte) error {
	*x = Resource{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain Resource
	return json.Unmarshal(data, (*plain)(x))
}

// NewServiceProbe returns a new ServiceProbe, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewServiceProbe() ServiceProbe {
	var value ServiceProbe
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero ServiceProbe.
func (x *ServiceProbe) applyDefaults() {
	x.LatencyMs = nil
	x.Status = "unknown"
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so ServiceProbe inside a list is defaulted exactly like one at the root.
func (x *ServiceProbe) UnmarshalJSON(data []byte) error {
	*x = ServiceProbe{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain ServiceProbe
	return json.Unmarshal(data, (*plain)(x))
}

// NewTerminalTarget returns a new TerminalTarget, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewTerminalTarget() TerminalTarget {
	var value TerminalTarget
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero TerminalTarget.
func (x *TerminalTarget) applyDefaults() {
	x.Cols = 80
	x.Kind = "session"
	x.Rows = 24
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so TerminalTarget inside a list is defaulted exactly like one at the root.
func (x *TerminalTarget) UnmarshalJSON(data []byte) error {
	*x = TerminalTarget{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain TerminalTarget
	return json.Unmarshal(data, (*plain)(x))
}

// NewUpdateStatus returns a new UpdateStatus, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewUpdateStatus() UpdateStatus {
	var value UpdateStatus
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero UpdateStatus.
func (x *UpdateStatus) applyDefaults() {
	x.Code = nil
	x.Message = ""
	x.ProgressPct = nil
	x.SessionPanes = 0
	x.ShellPanes = 0
	x.TargetVersion = nil
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so UpdateStatus inside a list is defaulted exactly like one at the root.
func (x *UpdateStatus) UnmarshalJSON(data []byte) error {
	*x = UpdateStatus{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain UpdateStatus
	return json.Unmarshal(data, (*plain)(x))
}

// NewUsageWindow returns a new UsageWindow, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewUsageWindow() UsageWindow {
	var value UsageWindow
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero UsageWindow.
func (x *UsageWindow) applyDefaults() {
	x.RemainingPct = nil
	x.ResetsAt = nil
	x.UsedPct = nil
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so UsageWindow inside a list is defaulted exactly like one at the root.
func (x *UsageWindow) UnmarshalJSON(data []byte) error {
	*x = UsageWindow{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain UsageWindow
	return json.Unmarshal(data, (*plain)(x))
}

// NewWorkingDiff returns a new WorkingDiff, seeded with every default the contract declares.
// Build values this way rather than as a struct literal: a literal leaves
// slices nil (they marshal to null, which the server rejects) and non-zero
// defaults unset.
func NewWorkingDiff() WorkingDiff {
	var value WorkingDiff
	value.applyDefaults()
	return value
}

// applyDefaults writes the contract's defaults over a zero WorkingDiff.
func (x *WorkingDiff) applyDefaults() {
	x.Dropped = 0
	x.Staged = []DiffFile{}
	x.Truncated = false
	x.Unstaged = []DiffFile{}
	x.Untracked = []DiffFile{}
}

// UnmarshalJSON seeds the defaults and then lets the incoming object write over
// them, which is what reproduces zod's "undefined -> default" at any depth: the
// standard decoder calls this same method for every nested object and every
// slice element, so WorkingDiff inside a list is defaulted exactly like one at the root.
func (x *WorkingDiff) UnmarshalJSON(data []byte) error {
	*x = WorkingDiff{}
	x.applyDefaults()
	// A local type with the same fields and none of the methods — without it this
	// call would recurse into itself.
	type plain WorkingDiff
	return json.Unmarshal(data, (*plain)(x))
}
