// Code generated by internal/protocol/gen. DO NOT EDIT.
//
// Source: packages/protocol/schema (generated in turn from packages/protocol/src/index.ts).
// Regenerate with: go generate ./internal/protocol

package protocol

// The contract these sources were generated from, pinned.
//
// A Go test hashes packages/protocol/schema/*.json and compares. That is the
// tripwire for the one failure this package cannot otherwise see: somebody edits
// the zod contract, regenerates the JSON artefacts, and does NOT re-run
// `go generate ./...`. The agent would then keep validating against a stale
// contract and quietly disagree with the server about a field neither side
// mentions. Re-running the generator is the fix.

const (
	// SchemaSHA256 is sha256 of packages/protocol/schema/protocol.schema.json.
	SchemaSHA256 = "7b0e17a9f1014c64908afaddc260b72ae0b06443def68eb5654a674571d534d4"
	// ConstantsSHA256 is sha256 of packages/protocol/schema/constants.json.
	ConstantsSHA256 = "08c0e2e885865abe19f27dd2f3ed1a870f1a613cb6ec21318fc076efcc13e4b5"
)
