// Code generated by internal/protocol/gen. DO NOT EDIT.
//
// Source: packages/protocol/schema (generated in turn from packages/protocol/src/index.ts).
// Regenerate with: go generate ./internal/protocol

package protocol

// The contract these sources were generated from, pinned.
//
// A Go test hashes packages/protocol/schema/*.json and compares. That is the
// tripwire for the one failure this package cannot otherwise see: somebody edits
// the zod contract, regenerates the JSON artefacts, and does NOT re-run
// `go generate ./...`. The agent would then keep validating against a stale
// contract and quietly disagree with the server about a field neither side
// mentions. Re-running the generator is the fix.

const (
	// SchemaSHA256 is sha256 of packages/protocol/schema/protocol.schema.json.
	SchemaSHA256 = "73f29f9158c92a816ba1925dadba9357fd4b7d4e75ee996ca9087b21e1b7847a"
	// ConstantsSHA256 is sha256 of packages/protocol/schema/constants.json.
	ConstantsSHA256 = "62ab5c364ddb8d7f1e77a0c81346254b87d8460a1f2cd2b78827470471114a5a"
)
