#!/usr/bin/env node
/**
 * Turn the zod contract into the JSON artefacts the Go agent embeds.
 *
 * WHY THIS EXISTS: `src/index.ts` is the single source of truth for the wire
 * shapes, and it says far more than "these fields exist" — it says which fields
 * may be absent, what a reader must substitute when they are, and which strings
 * are pattern-gated. Retyping that in Go would re-decide every one of those calls
 * by hand, and the disagreements would be silent: an agent that treats an absent
 * `heartbeatSec` as 0 does not fail, it just polls in a hot loop. So the Go side
 * reads a GENERATED artefact instead, and a drift check (`--check`) fails the
 * build the moment the generated bytes and the committed bytes disagree.
 *
 * TWO PROPERTIES THIS FILE MUST KEEP:
 *
 *  1. `additionalProperties: true`, everywhere. Every object in the protocol is
 *     zod's default `strip`, and `test/protocol.test.ts` (TC-PDPROTO-007) pins
 *     that an unknown field is ignored so a newer server keeps talking to an
 *     older agent. `zod-to-json-schema` emits `additionalProperties: false` for
 *     strip objects unless told otherwise — the exact inversion of that rule,
 *     which would make a schema-driven Go reader reject the frames zod accepts.
 *     `removeAdditionalStrategy: 'strict'` is the (badly named) option that means
 *     "a strip object allows additional properties"; `assertContract` then
 *     re-checks every emitted object, so the guarantee does not rest on an option
 *     name surviving a dependency bump.
 *
 *  2. Byte-identical output on every machine. Keys are sorted and the file ends
 *     in a newline, so `--check` compares bytes and a diff means a real change.
 *     Nothing derived from the clock, the path or the environment may enter the
 *     output — a `generatedAt` stamp would make every check fail and teach
 *     everyone to ignore it.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { zodToJsonSchema } from 'zod-to-json-schema';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = join(HERE, '..');
const SOURCE_ENTRY = join(PACKAGE_ROOT, 'src', 'index.ts');
const SCHEMA_DIR = join(PACKAGE_ROOT, 'schema');
const SCHEMA_FILE = join(SCHEMA_DIR, 'protocol.schema.json');
const CONSTANTS_FILE = join(SCHEMA_DIR, 'constants.json');

const REGENERATE_COMMAND = 'npm run schema:build -w @pdmux/protocol';
const GENERATED_NOTICE =
	`GENERATED FILE — do not hand-edit. Derived from packages/protocol/src/index.ts; ` +
	`regenerate with \`${REGENERATE_COMMAND}\`.`;

/**
 * The frames each side may send. Both are ordinary members of `$defs` so a Go
 * generator can map every `$defs` entry to a type with one rule; `roots` only
 * says which two of them are entry points.
 */
const ROOT_NAMES = ['agentUpstream', 'agentDownstream'];

/** Constants a schema cannot express, and therefore the first things to drift. */
const CONSTANT_NAMES = [
	// The close codes an agent is dropped with. Generated rather than restated
	// because the agent decides what to record from the NUMBER alone — if the two
	// sides disagree, a deliberate disconnect reads as a network blip.
	'AGENT_CLOSE_HOST_DELETED',
	'AGENT_CLOSE_HOST_DISABLED',
	'AGENT_CLOSE_REPLACED',
	'AGENT_CLOSE_TOKEN_REVOKED',
	'AGENT_KEY_HEADER',
	'AGENT_WS_PATH',
	'DIFF_CAPS',
	'EXEC_OUTPUT_MAX',
	'MIN_SUPPORTED_AGENT',
	'PROTOCOL_VERSION',
	'TERMINAL_WS_PATH',
];

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

/**
 * Every exported zod schema, keyed by its export name minus the `Schema` suffix.
 *
 * DISCOVERED, NOT LISTED: a hand-written list is a second place to forget a new
 * frame, and forgetting one here is silent — the Go side simply never learns the
 * type exists. `percent` and `epochSeconds` are exported without the suffix and
 * keep their own names; they MUST be named, because they are single zod
 * instances reused across many fields and an unnamed shared instance makes
 * `zod-to-json-schema` point later uses at wherever it happened to serialise the
 * first one (`#/$defs/usageWindow/properties/usedPct/anyOf/0`) — a ref that moves
 * whenever a field is reordered.
 */
function collectNamedSchemas(protocol) {
	/** @type {Record<string, unknown>} */
	const named = {};
	for (const [exportName, value] of Object.entries(protocol)) {
		if (!value || typeof value !== 'object') continue;
		if (typeof (/** @type {{ safeParse?: unknown }} */ (value).safeParse) !== 'function') continue;
		const name = exportName.endsWith('Schema') ? exportName.slice(0, -'Schema'.length) : exportName;
		if (name in named) throw new Error(`two exports map to the $defs name "${name}"`);
		named[name] = value;
	}
	for (const root of ROOT_NAMES) {
		if (!(root in named)) throw new Error(`root schema "${root}Schema" is not exported from src/index.ts`);
	}
	return named;
}

/**
 * Build both JSON documents from a loaded `@pdmux/protocol` module namespace.
 *
 * Pure on purpose: the artefact test calls this with the module it imported
 * itself, so "is the committed file current" is answered without spawning a
 * process, and it fails exactly the way `--check` does.
 *
 * @param {Record<string, unknown>} protocol the module namespace of src/index.ts
 * @returns {{ schema: Record<string, unknown>, constants: Record<string, unknown> }}
 */
export function buildSchema(protocol) {
	const named = collectNamedSchemas(protocol);

	// One pass over every named schema. Seeding `definitions` first is what makes
	// a shared sub-schema serialise once and be referenced by name everywhere else.
	const generated = zodToJsonSchema(/** @type {never} */ (named[ROOT_NAMES[0]]), {
		definitions: /** @type {never} */ (named),
		definitionPath: '$defs',
		$refStrategy: 'root',
		target: 'jsonSchema7',
		// "strict" = only an explicitly `.strict()` object rejects unknown keys.
		// Everything in this protocol is `strip`, so everything allows them.
		removeAdditionalStrategy: 'strict',
		errorMessages: false,
		markdownDescription: false,
	});

	const defs = /** @type {Record<string, Record<string, unknown>>} */ (generated.$defs);

	/** @type {Record<string, unknown>} */
	const schema = {
		$schema: 'http://json-schema.org/draft-07/schema#',
		$comment: GENERATED_NOTICE,
		title: 'pdmux agent protocol',
		// Annotations live at the document root, never inside a root schema, so
		// resolving `#/$defs/agentUpstream` yields exactly what zod validates.
		_generated: {
			doNotEdit: true,
			command: REGENERATE_COMMAND,
			source: 'packages/protocol/src/index.ts',
			generator: 'packages/protocol/scripts/build-schema.mjs',
			protocolVersion: protocol.PROTOCOL_VERSION,
		},
		roots: Object.fromEntries(ROOT_NAMES.map((name) => [name, { $ref: `#/$defs/${name}` }])),
		$defs: defs,
	};

	/** @type {Record<string, unknown>} */
	const constants = {
		$comment: GENERATED_NOTICE,
		_generated: {
			doNotEdit: true,
			command: REGENERATE_COMMAND,
			source: 'packages/protocol/src/index.ts',
			generator: 'packages/protocol/scripts/build-schema.mjs',
		},
	};
	for (const name of CONSTANT_NAMES) {
		if (!(name in protocol)) throw new Error(`constant ${name} is not exported from src/index.ts`);
		constants[name] = protocol[name];
	}

	assertContract(schema);
	return { schema: sortKeys(schema), constants: sortKeys(constants) };
}

/**
 * Re-check the properties the Go side depends on, on the emitted document rather
 * than on the options we passed. An option rename in a dependency bump would
 * otherwise flip `additionalProperties` fleet-wide and only show up as agents
 * dropping frames they should have accepted.
 *
 * @param {Record<string, unknown>} schema
 */
function assertContract(schema) {
	const defs = /** @type {Record<string, unknown>} */ (schema.$defs);
	const defNames = new Set(Object.keys(defs));
	/** @type {string[]} */
	const openObjects = [];
	/** @type {string[]} */
	const problems = [];

	walk(schema, '', (node, pointer) => {
		if (node.type === 'object') {
			if (node.additionalProperties === true) openObjects.push(pointer);
			else problems.push(`${pointer || '/'}: additionalProperties is ${JSON.stringify(node.additionalProperties)}, expected true`);
		}
		if (typeof node.$ref === 'string') {
			const match = /^#\/\$defs\/([A-Za-z][A-Za-z0-9]*)$/.exec(node.$ref);
			if (!match) problems.push(`${pointer}/$ref: "${node.$ref}" does not name a top-level $def`);
			else if (!defNames.has(match[1])) problems.push(`${pointer}/$ref: "${node.$ref}" has no target in $defs`);
		}
	});

	if (openObjects.length < 20) {
		problems.push(`only ${openObjects.length} objects were inspected — the walk is not reaching the schema`);
	}
	if (problems.length > 0) {
		throw new Error(`the generated schema breaks the protocol's contract:\n  ${problems.join('\n  ')}`);
	}
}

/**
 * @param {unknown} node
 * @param {string} pointer
 * @param {(node: Record<string, any>, pointer: string) => void} visit
 */
function walk(node, pointer, visit) {
	if (Array.isArray(node)) {
		node.forEach((item, index) => walk(item, `${pointer}/${index}`, visit));
		return;
	}
	if (!isPlainObject(node)) return;
	visit(node, pointer);
	for (const [key, value] of Object.entries(node)) walk(value, `${pointer}/${escapePointer(key)}`, visit);
}

// ---------------------------------------------------------------------------
// Serialisation
// ---------------------------------------------------------------------------

/** Recursively sort object keys. Arrays keep their order — it is meaningful (`anyOf`, `enum`, `required`). */
function sortKeys(value) {
	if (Array.isArray(value)) return value.map(sortKeys);
	if (!isPlainObject(value)) return value;
	/** @type {Record<string, unknown>} */
	const out = {};
	for (const key of Object.keys(value).sort()) out[key] = sortKeys(value[key]);
	return out;
}

/** The exact bytes that belong on disk: sorted, 2-space indented, newline-terminated. */
export function serialize(value) {
	return `${JSON.stringify(sortKeys(value), null, 2)}\n`;
}

function isPlainObject(value) {
	return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function escapePointer(key) {
	return key.replace(/~/g, '~0').replace(/\//g, '~1');
}

// ---------------------------------------------------------------------------
// Diffing (--check)
// ---------------------------------------------------------------------------

const MAX_REPORTED_DIFFS = 40;

/**
 * Every place the committed document and the generated one disagree, as JSON
 * pointers — the form that says WHICH field moved, rather than which line did.
 *
 * @returns {{ pointer: string, kind: 'added' | 'removed' | 'changed', committed?: unknown, generated?: unknown }[]}
 */
export function diffPointers(committed, generated, pointer = '', out = []) {
	if (out.length >= MAX_REPORTED_DIFFS) return out;
	if (isPlainObject(committed) && isPlainObject(generated)) {
		const keys = [...new Set([...Object.keys(committed), ...Object.keys(generated)])].sort();
		for (const key of keys) {
			const child = `${pointer}/${escapePointer(key)}`;
			if (!(key in committed)) out.push({ pointer: child, kind: 'added', generated: generated[key] });
			else if (!(key in generated)) out.push({ pointer: child, kind: 'removed', committed: committed[key] });
			else diffPointers(committed[key], generated[key], child, out);
		}
		return out;
	}
	if (Array.isArray(committed) && Array.isArray(generated)) {
		for (let index = 0; index < Math.max(committed.length, generated.length); index += 1) {
			const child = `${pointer}/${index}`;
			if (index >= committed.length) out.push({ pointer: child, kind: 'added', generated: generated[index] });
			else if (index >= generated.length) out.push({ pointer: child, kind: 'removed', committed: committed[index] });
			else diffPointers(committed[index], generated[index], child, out);
		}
		return out;
	}
	if (!Object.is(committed, generated)) {
		out.push({ pointer: pointer || '/', kind: 'changed', committed, generated });
	}
	return out;
}

function preview(value) {
	const text = JSON.stringify(value);
	if (text === undefined) return 'undefined';
	return text.length > 120 ? `${text.slice(0, 117)}...` : text;
}

/** Byte-level fallback: the values match but the file does not, so the FORMATTING drifted. */
function firstLineDifference(committedText, generatedText) {
	const committed = committedText.split('\n');
	const generated = generatedText.split('\n');
	for (let index = 0; index < Math.max(committed.length, generated.length); index += 1) {
		if (committed[index] === generated[index]) continue;
		const from = Math.max(0, index - 2);
		const lines = [];
		for (let context = from; context < index; context += 1) lines.push(`  ${context + 1} | ${committed[context]}`);
		lines.push(`- ${index + 1} | ${committed[index] ?? '(end of file)'}`);
		lines.push(`+ ${index + 1} | ${generated[index] ?? '(end of file)'}`);
		return lines.join('\n');
	}
	return '(files differ only in trailing bytes)';
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

/**
 * Load the contract from SOURCE, not from `dist/`.
 *
 * A stale `dist/` would generate a stale artefact and pass its own check, which
 * is the one failure mode this whole file exists to prevent. Node strips the
 * types itself; the resolve hook only exists because TypeScript's ESM style
 * writes `./semver.js` for a file that is on disk as `./semver.ts`.
 */
async function loadProtocol() {
	const { registerHooks } = await import('node:module');
	if (typeof registerHooks === 'function') {
		const srcDir = pathToFileURL(join(PACKAGE_ROOT, 'src')).href;
		registerHooks({
			resolve(specifier, context, nextResolve) {
				if (specifier.startsWith('.') && specifier.endsWith('.js') && context.parentURL?.startsWith(srcDir)) {
					return nextResolve(`${specifier.slice(0, -'.js'.length)}.ts`, context);
				}
				return nextResolve(specifier, context);
			},
		});
	}
	return import(pathToFileURL(SOURCE_ENTRY).href);
}

async function main(argv) {
	const check = argv.includes('--check');
	const protocol = await loadProtocol();
	const { schema, constants } = buildSchema(protocol);
	const files = [
		{ path: SCHEMA_FILE, text: serialize(schema), value: schema },
		{ path: CONSTANTS_FILE, text: serialize(constants), value: constants },
	];

	if (!check) {
		mkdirSync(SCHEMA_DIR, { recursive: true });
		for (const file of files) {
			writeFileSync(file.path, file.text);
			const bytes = Buffer.byteLength(file.text);
			console.log(`wrote ${relative(process.cwd(), file.path)} (${bytes} bytes)`);
		}
		return 0;
	}

	let stale = false;
	for (const file of files) {
		const shown = relative(process.cwd(), file.path);
		if (!existsSync(file.path)) {
			console.error(`${shown} is missing — run \`${REGENERATE_COMMAND}\``);
			stale = true;
			continue;
		}
		const committedText = readFileSync(file.path, 'utf8');
		if (committedText === file.text) {
			console.log(`${shown} is up to date`);
			continue;
		}
		stale = true;
		console.error(`${shown} is out of date — run \`${REGENERATE_COMMAND}\``);
		let committedValue;
		try {
			committedValue = JSON.parse(committedText);
		} catch (error) {
			console.error(`  the committed file is not valid JSON: ${error instanceof Error ? error.message : error}`);
			continue;
		}
		const diffs = diffPointers(committedValue, file.value);
		if (diffs.length === 0) {
			console.error('  the values match but the bytes do not — formatting drifted:');
			console.error(firstLineDifference(committedText, file.text));
			continue;
		}
		for (const diff of diffs.slice(0, MAX_REPORTED_DIFFS)) {
			if (diff.kind === 'added') console.error(`  + ${diff.pointer}  ${preview(diff.generated)}`);
			else if (diff.kind === 'removed') console.error(`  - ${diff.pointer}  ${preview(diff.committed)}`);
			else console.error(`  ~ ${diff.pointer}  ${preview(diff.committed)} -> ${preview(diff.generated)}`);
		}
		if (diffs.length >= MAX_REPORTED_DIFFS) console.error(`  ... and more (stopped after ${MAX_REPORTED_DIFFS})`);
	}
	return stale ? 1 : 0;
}

const invokedDirectly = process.argv[1] !== undefined && pathToFileURL(process.argv[1]).href === import.meta.url;
if (invokedDirectly) {
	process.exitCode = await main(process.argv.slice(2));
}
