export const PDMUX_HTTP_ROUTES = [
  "GET /fleet/scope",
  "GET /fleet/settings",
  "PUT /fleet/settings",
  "POST /integrations/cloudflare/discover",
  "GET /integrations/cloudflare",
  "PUT /integrations/cloudflare",
  "DELETE /integrations/cloudflare",
  "GET /hosts",
  "GET /hosts/:hostId",
  "POST /hosts",
  "PATCH /hosts/:hostId",
  "DELETE /hosts/:hostId",
  "PUT /hosts/:hostId/enabled",
  "POST /hosts/:hostId/move",
  "PUT /hosts/reorder",
  "GET /hosts/:hostId/services",
  "POST /hosts/:hostId/services",
  "PUT /hosts/:hostId/services/reorder",
  "PATCH /hosts/:hostId/services/:id",
  "DELETE /hosts/:hostId/services/:id",
  "GET /hosts/:hostId/exposures",
  "POST /hosts/:hostId/services/:id/exposures",
  "PATCH /hosts/:hostId/services/:id/exposures/:exposureId",
  "DELETE /hosts/:hostId/services/:id/exposures/:exposureId",
  "GET /hosts/:hostId/git-roots",
  "POST /hosts/:hostId/git-roots",
  "PATCH /hosts/:hostId/git-roots/:id",
  "DELETE /hosts/:hostId/git-roots/:id",
  "GET /hosts/:hostId/repos",
  "GET /hosts/:hostId/repos/:repoId",
  "GET /hosts/:hostId/repos/:repoId/working-diff",
  "GET /hosts/:hostId/repos/:repoId/commits/:sha/detail",
  "GET /hosts/:hostId/repos/:repoId/commits/:sha/tree",
  "GET /hosts/:hostId/repos/:repoId/commits/:sha/blob",
  "GET /hosts/:hostId/metrics",
  "POST /hosts/:hostId/collect",
  "POST /agent/enroll",
  "GET /agent-auth-failures",
  "POST /hosts/:hostId/enrollments",
  "GET /hosts/:hostId/enrollments/current",
  "DELETE /hosts/:hostId/enrollments/:id",
  "GET /hosts/:hostId/tokens",
  "POST /hosts/:hostId/tokens",
  "POST /hosts/:hostId/tokens/:id/rotate",
  "DELETE /hosts/:hostId/tokens/:id",
  "POST /hosts/:hostId/agent/update",
  "POST /fleet/agent/update",
  "GET /hosts/:hostId/files",
  "GET /hosts/:hostId/files/content",
  "GET /hosts/:hostId/files/download",
  "POST /hosts/:hostId/files/upload",
  "DELETE /hosts/:hostId/files",
  "GET /prefs",
  "PUT /prefs/layouts/:name",
  "DELETE /prefs/layouts/:name",
  "PUT /prefs/hosts/:hostId",
  "POST /terminal/:hostId/copy-mode",
  "POST /terminal/:hostId/history",
  "GET /hosts/:hostId/mcp-keys",
  "POST /hosts/:hostId/mcp-keys",
  "DELETE /hosts/:hostId/mcp-keys/:id",
  "GET /account/mcp-tokens/policy",
  "GET /account/mcp-tokens",
  "POST /account/mcp-tokens",
  "DELETE /account/mcp-tokens/:id",
  "ALL /mcp",
  "GET /agent-kit/manifest",
  "GET /agent-kit",
] as const;

export const PDMUX_WEBSOCKET_ROUTES = ["WS /agent/ws", "WS /terminal/ws"] as const;

const HIDDEN_HTTP_ROUTES = new Set(["ALL /mcp", "GET /agent-kit/manifest", "GET /agent-kit"]);

export const PDMUX_DOCUMENTED_HTTP_ROUTES = PDMUX_HTTP_ROUTES
  .filter((route) => !HIDDEN_HTTP_ROUTES.has(route))
  .map((route) => route.replace(/:([A-Za-z][A-Za-z0-9_]*)/g, "{$1}"));
