import { test as base, expect, type APIRequestContext, type APIResponse } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { execFile, spawn } from "node:child_process";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { promisify } from "node:util";
import { StackManager, type StackAddresses } from "../../apps/desktop/src/stack-manager";

const repository = resolve(__dirname, "../..");
const execute = promisify(execFile);
const emails = ["readiness-owner@example.com", "readiness-other@example.com"];

export interface ReadinessRuntime extends StackAddresses {
  owner: APIRequestContext;
  other: APIRequestContext;
  container: string;
  executeAgent: (args: string[]) => Promise<string>;
  installAgent: (command: string) => Promise<void>;
}

export async function json<T>(response: APIResponse): Promise<T> {
  expect(response.ok(), `${response.url()} returned ${response.status()}: ${response.ok() ? "" : await response.text()}`).toBe(true);
  return await response.json() as T;
}

export const test = base.extend<object, { runtime: ReadinessRuntime }>({
  runtime: [async ({ playwright }, use): Promise<void> => {
    const temporary = await mkdtemp(join(tmpdir(), "pdmux-readiness-"));
    const container = `pdmux-readiness-${randomUUID()}`;
    const password = `${randomUUID()}!Az9`;
    const postgresContainer = `${container}-postgres`;
    let databaseEnvironment: NodeJS.ProcessEnv = {};
    const stack = new StackManager({
      bunExecutable: "bun",
      apiEntry: join(repository, "apps/api/dist/main.js"),
      migrateEntry: join(repository, "apps/api/dist/migrate.js"),
      webEntry: join(repository, "apps/web/build/index.js"),
      dataDirectory: temporary,
      filesDirectory: join(temporary, "files"),
      databasePath: join(temporary, "pdmux.sqlite"),
      secretPath: join(temporary, "auth-secret"),
      agentReleaseDirectory: join(repository, "apps/web/static/agent"),
    }, {
      spawn: (command, args, options) => spawn(command, [...args], {
        ...options,
        // The application's supported bootstrap policy; no direct database writes.
        env: { ...options.env, ...databaseEnvironment, ADMIN_EMAILS: emails.join(","), AUTH_REQUIRE_SIGNUP_APPROVAL: "false", AUTH_HIBP_ENABLED: "false", AUDIT_LOG_ENABLED: "true" },
      }),
    });
    const contexts: APIRequestContext[] = [];
    try {
      if (process.env.READINESS_DATABASE === "postgres") {
        await execute("docker", ["run", "--detach", "--name", postgresContainer, "--publish", "127.0.0.1::5432", "--env", "POSTGRES_HOST_AUTH_METHOD=trust", "--env", "POSTGRES_DB=pdmux", "postgres:16-alpine"]);
        const address = (await execute("docker", ["port", postgresContainer, "5432/tcp"])).stdout.trim();
        databaseEnvironment = { PDMUX_DATABASE_PROVIDER: "postgres", DATABASE_URL: `postgres://postgres@${address}/pdmux`, POSTGRES_HOST: "127.0.0.1", POSTGRES_PORT: address.split(":")[1], POSTGRES_USER: "postgres", POSTGRES_PASSWORD: password, POSTGRES_DB: "pdmux" };
        await expect.poll(async () => (await execute("docker", ["exec", postgresContainer, "pg_isready", "-U", "postgres"]).catch(() => ({ stdout: "" }))).stdout, { timeout: 30_000 }).toContain("accepting connections");
      }
      const addresses = await stack.start();
      await execute("docker", ["build", "-f", join(repository, "tests/readiness/Dockerfile.agent"), "-t", "pdmux-readiness-agent:local", join(repository, "tests/readiness")], { timeout: 180_000 });
      await execute("docker", ["run", "--detach", "--name", container, "--network", "host", "pdmux-readiness-agent:local"]);
      for (const [index, email] of emails.entries()) {
        const context = await playwright.request.newContext({ baseURL: addresses.webUrl, extraHTTPHeaders: { origin: addresses.webUrl } });
        contexts.push(context);
        await json(await context.post("/api/auth/sign-up/email", { data: { name: `Readiness ${index}`, email, password } }));
        await json(await context.post("/api/auth/sign-in/email", { data: { email, password } }));
      }
      const [owner, other] = contexts;
      if (!owner || !other) throw new Error("Missing isolated accounts");
      await use({
        ...addresses, owner, other, container,
        executeAgent: async (args): Promise<string> => (await execute("docker", ["exec", container, ...args], { timeout: 60_000 })).stdout,
        installAgent: async (command): Promise<void> => {
          // Execute only the installer generated by this loopback stack, inside a
          // disposable container. Service-manager integration needs a native VM.
          const prefix = `curl -fsSL ${addresses.webUrl}/install.sh | sh -s -- --code `;
          if (!command.startsWith(prefix) || !/^pdmxe_[A-Za-z0-9-]+$/.test(command.slice(prefix.length))) {
            throw new Error(`Unexpected MCP installation origin: ${command.split(" --code ")[0]}; expected ${addresses.webUrl}`);
          }
          await new Promise<void>((accept, reject) => {
            const child = spawn("docker", ["exec", "-i", container, "sh"], { stdio: ["pipe", "ignore", "pipe"], timeout: 60_000 });
            let errors = "";
            child.stderr.on("data", (data: Buffer) => { errors += data.toString(); });
            child.once("error", reject);
            child.once("exit", code => code === 0 ? accept() : reject(new Error(`Installer failed (${code}): ${errors.replace(/pdmxe_[A-Za-z0-9-]+/g, "[redacted]")}`)));
            child.stdin.end(`${command} --no-service\n`);
          });
          await execute("docker", ["exec", "--detach", container, "/usr/local/bin/pdmux-agent", "run", "--config", "/etc/pdmux/agent.json"]);
        },
      });
    } finally {
      await execute("docker", ["rm", "--force", container]).catch(() => undefined);
      await Promise.all(contexts.map(context => context.dispose()));
      await stack.stop();
      if (process.env.READINESS_DATABASE === "postgres") await execute("docker", ["rm", "--force", postgresContainer]).catch(() => undefined);
      await rm(temporary, { recursive: true, force: true });
    }
  }, { scope: "worker", timeout: 240_000 }],
});

export { expect };
